name: actionlint

on:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - .github/workflows/**

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-check
